{% set data = load_setup_py_data() %}

package:
  name: autoroi
  version: {{ data['version'] }}

source:
  path: ..

build:
  number: 0
  script: python setup.py install --single-version-externally-managed --record=record.txt

requirements:
  build:
    - python
    - setuptools

  run:
    - python
    - numpy >=1.16
    - pwspy
    - h5py
    - tensorflow

about:
  home: data['url']

  summary: data['description']
  description: data['long_description']
  dev_url: data['url']